//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilverlightContrib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilverlightContrib.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion not supported.
        /// </summary>
        public static string ExceptionConversionNotSupported {
            get {
                return ResourceManager.GetString("ExceptionConversionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emf source cannot be re-used over multiple Emf controls.
        /// </summary>
        public static string ExceptionEmfSourceReuse {
            get {
                return ResourceManager.GetString("ExceptionEmfSourceReuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of stream reached while expecting more data.
        /// </summary>
        public static string ExceptionEndOfStream {
            get {
                return ResourceManager.GetString("ExceptionEndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not contain Enhanced Metafile data.
        /// </summary>
        public static string ExceptionNoEmfStream {
            get {
                return ResourceManager.GetString("ExceptionNoEmfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of string value {0} does not fit in range [{1}..{2}].
        /// </summary>
        public static string ExceptionStringLength {
            get {
                return ResourceManager.GetString("ExceptionStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Metafile function {0} not supported.
        /// </summary>
        public static string MessageEmfFunctionNotSupported {
            get {
                return ResourceManager.GetString("MessageEmfFunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Metafile function {0:X} unknown.
        /// </summary>
        public static string MessageEmfFunctionUnknown {
            get {
                return ResourceManager.GetString("MessageEmfFunctionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while writing XAML. Details:.
        /// </summary>
        public static string MessageXamlError {
            get {
                return ResourceManager.GetString("MessageXamlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML for {0} not implemented yet.
        /// </summary>
        public static string MessageXamlNotImplemented {
            get {
                return ResourceManager.GetString("MessageXamlNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML for Path Data is not available due to Silverlight runtime limitations.
        /// </summary>
        public static string MessageXamlPathDataNotSupported {
            get {
                return ResourceManager.GetString("MessageXamlPathDataNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML truncated, reached the specified maximum number of {0} UI elements.
        /// </summary>
        public static string MessageXamlTruncated {
            get {
                return ResourceManager.GetString("MessageXamlTruncated", resourceCulture);
            }
        }
    }
}
