name: OpenSilver.SilverlightContrib Build

on:
  workflow_dispatch:
    inputs:
        opensilver-version:
            description: 'OpenSilver version'
            required: true
        version:
            description: 'OpenSilver.SilverlightContrib package version'
            required: true

jobs:
  Build-Pack-Publish:
    if: github.repository_owner == 'OpenSilver'
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1.1
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Clone SilverlightContrib repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build OpenSilver.SilverlightContrib NuGet package
        run: ./build/Build_NuGet.bat ${{ github.event.inputs.version }} ${{ github.event.inputs.opensilver-version }}
      - name: Upload packages to MyGet
        run: |
           dotnet nuget push "build\output\*.nupkg" -k ${{ secrets.MYGET_TOKEN }} -s https://www.myget.org/F/opensilver/api/v2/package